# Generated by Django 4.1 on 2022-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Current_Bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='Final_price',
            field=models.IntegerField(default=0),
        ),
    ]
