# Generated by Django 4.1 on 2022-09-28 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_user_id_bid_bidder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=264)),
                ('Commenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listing', to='auctions.listing')),
            ],
        ),
    ]
