# Generated by Django 4.1 on 2022-09-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='caption',
            field=models.CharField(default='Image ofListing ', max_length=64),
        ),
    ]
