# Generated by Django 4.1 on 2022-09-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='f', upload_to='images'),
            preserve_default=False,
        ),
    ]
