# Generated by Django 4.1 on 2022-09-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Final_price',
            new_name='Highest_Bid',
        ),
    ]
